stages:
  - deploy

deploy:
  image: alpine
  stage: deploy
  before_script:
    - apk add --no-cache lftp
  script:
    - echo "📁 Création du dossier deploy/"
    - mkdir deploy
    - echo "📦 Copie des fichiers nécessaires dans deploy/"
    - cp server.js package.json deploy/
    - cp -r src deploy/
    - cp .env deploy/ || echo "Pas de .env en local, ignoré"
    - echo "🔢 Nombre de fichiers à déployer :"
    - find deploy -type f | wc -l
    - echo "🚀 Déploiement du dossier deploy/ vers api.empreinte-app.fr (FTP debug ON)"
    - lftp -d -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASS ftp.dalo8522.odns.fr; mirror -R --delete deploy/ ./"
