stages:
  - deploy

deploy:
  image: alpine
  stage: deploy
  before_script:
    - apk add --no-cache lftp
  script:
    - echo "Déploiement backend API sur O2Switch..."
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASS ftp.dalo8522.odns.fr; mirror -R --delete ./ ./"
